name: React App Test and Build

on:
  push:
    branches: [ main, develop, feature/* ]
  pull_request:
    branches: [ main, develop ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Run tests
      run: npm test -- --watchAll=false
      
    - name: Generate test coverage
      run: npm test -- --watchAll=false --coverage
      
    # Utilisation de la version 4 de upload-artifact (plus récente et plus fiable)
    - name: Upload test coverage
      uses: actions/upload-artifact@v4  # Mise à jour de v3 à v4
      with:
        name: coverage-report
        path: coverage
        retention-days: 5

  build:
    runs-on: ubuntu-latest
    needs: test
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Build
      run: npm run build
      
    # Utilisation de la version 4 de upload-artifact
    - name: Upload build
      uses: actions/upload-artifact@v4  # Mise à jour de v3 à v4
      with:
        name: build
        path: build
        retention-days: 5
